version: '3.3'

services:
   db:
     image: mysql:5.7
     container_name: db
     volumes:
       - db_data:/var/lib/mysql
     restart: unless-stopped
     env_file: .env
     environment:
       - MYSQL_DATABASE=wordpress


   wordpress:
     depends_on:
       - db
     image: wordpress:5.1.1-fpm-alpine
     container_name: wordpress
     volumes:
      - wordpress:/var/www/html
     restart: unless-stopped
     env_file: .env
     environment:
       - WORDPRESS_DB_HOST=db:3306
       - WORDPRESS_DB_USER=$MYSQL_USER
       - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
       - WORDPRESS_DB_NAME=wordpress


   webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - wordpress:/var/www/html


volumes:
  db_data:
  wordpress:


   